# Generated by Django 5.0.3 on 2024-04-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0004_alter_errorimages_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorImages',
        ),
    ]
