# Generated by Django 5.0.3 on 2024-04-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0005_delete_errorimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('img', models.ImageField(height_field=10, upload_to='error/', width_field=10)),
            ],
            options={
                'verbose_name': 'Зображення помилкі',
                'verbose_name_plural': 'Зображення помилкі',
            },
        ),
    ]
