# Generated by Django 5.0.3 on 2024-04-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0007_alter_errorimages_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorImages',
        ),
    ]
